version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /kotlin
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: uv
    directory: /python
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - "*"
